/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectopractico1;

import javax.swing.JOptionPane;

/**
 *
 * @author Charly Cimino
 */
public class calculadora01 extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(calculadora01.class.getName());

    /**
     * Creates new form formulario1
     */
     calculadora calc = new calculadora();

   

    public calculadora01() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jtitulo = new javax.swing.JLabel();
        JoperacionSuma = new javax.swing.JButton();
        Joperacionresta = new javax.swing.JButton();
        Joperaciondivision = new javax.swing.JButton();
        JoperacionMultiplicacion = new javax.swing.JButton();
        jvalor1 = new javax.swing.JTextField();
        jvalor2 = new javax.swing.JTextField();
        jResultadoOperacion = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        JResultado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jtitulo.setText("jcalculadora");

        JoperacionSuma.setText("suma");
        JoperacionSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JoperacionSumaActionPerformed(evt);
            }
        });

        Joperacionresta.setText("resta");
        Joperacionresta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JoperacionrestaActionPerformed(evt);
            }
        });

        Joperaciondivision.setText("division");
        Joperaciondivision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JoperaciondivisionActionPerformed(evt);
            }
        });

        JoperacionMultiplicacion.setText("multiplicacion");
        JoperacionMultiplicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JoperacionMultiplicacionActionPerformed(evt);
            }
        });

        jvalor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jvalor1ActionPerformed(evt);
            }
        });

        jResultadoOperacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jResultadoOperacionActionPerformed(evt);
            }
        });

        jLabel2.setText("ingresar el primer valor");

        jLabel3.setText("ingresar el segundo valor");

        JResultado.setText("resultado");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jtitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(JResultado)
                            .addComponent(JoperacionSuma))
                        .addGap(18, 18, 18)
                        .addComponent(Joperacionresta)
                        .addGap(18, 18, 18)
                        .addComponent(Joperaciondivision)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JoperacionMultiplicacion))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(18, 18, 18)
                                    .addComponent(jvalor1))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jvalor2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(160, 160, 160)
                                .addComponent(jResultadoOperacion, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(209, 209, 209))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jtitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(19, 19, 19)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jvalor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jvalor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JResultado)
                    .addComponent(jResultadoOperacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JoperacionSuma)
                    .addComponent(Joperacionresta)
                    .addComponent(Joperaciondivision)
                    .addComponent(JoperacionMultiplicacion))
                .addGap(0, 380, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JoperacionSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JoperacionSumaActionPerformed
        // TODO add your handling code here:
   {                                               
    try {
        double a = Double.parseDouble(jvalor1.getText());
        double b = Double.parseDouble(jvalor2.getText());

        double r = calc.sumar(a, b);

        jResultadoOperacion.setText(String.valueOf(r));
    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(this, "Debes ingresar números válidos.");
    }
}

    }//GEN-LAST:event_JoperacionSumaActionPerformed

    private void jvalor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jvalor1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jvalor1ActionPerformed

    private void jResultadoOperacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jResultadoOperacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jResultadoOperacionActionPerformed

    private void JoperacionrestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JoperacionrestaActionPerformed
        // TODO add your handling code here:
   try {
    double a = Double.parseDouble(jvalor1.getText());
    double b = Double.parseDouble(jvalor2.getText());

    double r = calc.restar(a, b);  

    jResultadoOperacion.setText(String.valueOf(r));

} catch (NumberFormatException ex) {
    JOptionPane.showMessageDialog(this, "Debes ingresar números válidos.");
}

    }//GEN-LAST:event_JoperacionrestaActionPerformed

    private void JoperaciondivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JoperaciondivisionActionPerformed
        // TODO add your handling code here:
        try {
    double a = Double.parseDouble(jvalor1.getText());
    double b = Double.parseDouble(jvalor2.getText());

    double r = calc.dividir(a, b);  

    jResultadoOperacion.setText(String.valueOf(r));

} catch (NumberFormatException ex) {
    JOptionPane.showMessageDialog(this, "Debes ingresar números válidos.");
}

    }//GEN-LAST:event_JoperaciondivisionActionPerformed

    private void JoperacionMultiplicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JoperacionMultiplicacionActionPerformed
        // TODO add your handling code here:
        try {
    double a = Double.parseDouble(jvalor1.getText());
    double b = Double.parseDouble(jvalor2.getText());

    double r = calc.multiplicar(a, b);  

    jResultadoOperacion.setText(String.valueOf(r));

} catch (NumberFormatException ex) {
    JOptionPane.showMessageDialog(this, "Debes ingresar números válidos.");
}

    }//GEN-LAST:event_JoperacionMultiplicacionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new calculadora01().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JResultado;
    private javax.swing.JButton JoperacionMultiplicacion;
    private javax.swing.JButton JoperacionSuma;
    private javax.swing.JButton Joperaciondivision;
    private javax.swing.JButton Joperacionresta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jResultadoOperacion;
    private javax.swing.JLabel jtitulo;
    private javax.swing.JTextField jvalor1;
    private javax.swing.JTextField jvalor2;
    // End of variables declaration//GEN-END:variables
}
